### ISSUE TITLE
Проблеми з паками, які містять в собі JS розширення

### ISSUE THREAD

**Issue by ArtemiiKravchuk** [mavka-ukr/mavka#42]
При спробі імпортувати модуль `fs` на Windows (протестовано на Windows11), виникає помилка (раніше такого не було):
![image](https://user-images.githubusercontent.com/115405408/232885181-5c45a1d1-296b-40fa-bdf1-d75788b2e06b.png)

Відповідно, пак фс пофіксив це для лінукса у версії 0.0.4, але на Windows все ще не працює:
![image](https://user-images.githubusercontent.com/115405408/232885487-08d8ddbf-ee63-4222-b11a-fc7045cc9772.png)

**Comment by denkisil** [comment]
тут не в імпортувані вбудованого модулю NodeJs, а в імпортувані самого розширення

**Comment by denkisil** [comment]
все працює
